doctrine:
    orm:
        default_entity_manager: default
        auto_generate_proxy_classes: '%kernel.debug%'
        auto_mapping: true
    dbal:
        default_connection: default
        connections:
            default:
                mapping_types:
                    enum: string
                    bit: boolean
                driver: pdo_mysql
                host: '%env(DB_HOST)%'
                port: '%env(DB_PORT)%'
                dbname: '%env(DB_NAME)%'
                user: '%env(DB_USER)%'
                password: '%env(DB_PASSWORD)%'
                charset: utf8mb4
                server_version: '%env(DB_SERVER_VERSION)%'
