version: '3.4'
services:

    royal-filter-adminer:
        image: adminer:latest
        container_name: royal-filter-adminer
        ports:
            - 8750:8080
        labels:
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:royal-filter-adminer.local-127-0-0-1.nip.io
            - traefik.enable=true
            - traefik.port=8080
        depends_on:
            - royal-filter-db
        networks:
            - alpin
            - traefik
        env_file:
            - .env.docker

    royal-filter-elasticsearch:
        image: elasticsearch:8.7.0
        container_name: royal-filter-elasticsearch
        volumes:
            - esdata01:/usr/share/elasticsearch/data
        ports:
            - '9270:9200'
            - '9370:9300'
        mem_limit: '2147483648'
        environment:
            - discovery.type=single-node
        networks:
            - alpin
            - traefik
        env_file:
            - .env.docker

    royal-filter-rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: royal-filter-rabbitmq
        volumes:
            - ./var/rabbitmq/data/:/var/lib/rabbitmq
        ports:
            - '5670:5672'
            - '15670:15672'
        labels:
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:royal-filter-rabbitmq.local-127-0-0-1.nip.io
            - traefik.frontend.passHostHeader=true
            - traefik.enable=true
            - traefik.port=15672
        networks:
            - alpin
            - traefik
        env_file:
            - .env.docker

    royal-filter-redis:
        image: redis:6.0-alpine
        container_name: royal-filter-redis
        ports:
            - "8970:6379"
        networks:
            - alpin
            - traefik
        env_file:
            - .env.docker

    royal-filter-db:
        image: mysql:8.0.32
        container_name: royal-filter-mysql
        working_dir: /application
        command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
        volumes:
            - ./:/var/www/html
            - ./var/mysql-data:/var/lib/mysql
            - ./.docker/mysql/init-scripts/:/docker-entrypoint-initdb.d
        ports:
            - "25070:3306"
        networks:
            - alpin
            - traefik
        env_file:
            - .env.docker

    royal-filter-webserver:
        image: nginx:1-alpine
        container_name: royal-filter-webserver
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
            - ./var/nginx-log/:/var/logs/nginx
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8070:80"
        labels:
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:royal-filter.local-127-0-0-1.nip.io
            - traefik.frontend.passHostHeader=true
            - traefik.enable=true
            - traefik.port=80
        depends_on:
            - royal-filter-php
        networks:
            - alpin
            - traefik
        env_file:
            - .env.docker

    royal-filter-webserver-debug:
        image: nginx:1-alpine
        container_name: royal-filter-webserver-debug
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
            - ./var/nginx-log/:/var/logs/nginx
            - ./.docker/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - "8071:80"
        labels:
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:royal-filter-debug.local-127-0-0-1.nip.io
            - traefik.frontend.passHostHeader=true
            - traefik.enable=true
            - traefik.port=80
        depends_on:
            - royal-filter-php-debug
        networks:
            - traefik
        env_file:
            - .env.docker

    royal-filter-php:
        image: devalpin11/pimcore-php:v11.x-latest
        container_name: royal-filter-php
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
        ports:
            - "35071:9000"
        depends_on:
            - royal-filter-db
            - royal-filter-redis
        networks:
            - alpin
            - traefik
        environment:
            - PHP_IDE_CONFIG="serverName=localhost"

    royal-filter-php-debug:
        image: devalpin11/pimcore-php:v11.x-latest
        container_name: royal-filter-php-debug
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html:cached
        ports:
            - "35072:9000"
        depends_on:
            - royal-filter-db
            - royal-filter-redis
        networks:
            - alpin
            - traefik
        environment:
            - PHP_IDE_CONFIG="serverName=localhost"
        env_file:
            - .env.docker

    royal-filter-blackfire:
        image: blackfire/blackfire:2
        container_name: royal-filter-blackfire
        ports:
            - "8374:8307"
        networks:
            - alpin
            - traefik
        env_file:
            - .env.docker

    royal-filter-mailhog:
        container_name: royal-filter-mailhog
        image: mailhog/mailhog
        environment:
            - MH_STORAGE=maildir
        volumes:
            - ./var/mailhog/maildir:/maildir:rw,delegated
        ports:
            - "1170:1025"
            - "8170:8025"
        depends_on:
            - royal-filter-webserver
            - royal-filter-webserver-debug
        labels:
            - traefik.docker.network=traefik
            - traefik.frontend.rule=Host:royal-filter-mailhog.local-127-0-0-1.nip.io
            - traefik.enable=true
            - traefik.port=8025
        networks:
            - alpin
            - traefik

    royal-filter-supervisord:
        #user: '1000:1000' # set to your uid:gid
        image: pimcore/pimcore:supervisord
        depends_on:
            - royal-filter-db
        volumes:
            - .:/var/www/html:cached
            - ./.docker/supervisord.conf:/etc/supervisor/conf.d/pimcore.conf:ro
        networks:
            - alpin
            - traefik

networks:
    alpin:
        internal: true
    traefik:
        external: true

volumes:
    esdata01:
        driver: local
